language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: T7RrRfOHV/oGaQb0ukmCZEHnAoP78IQk0EyJ6nkEeh5U1irOx8Xk+N0zDFkP+Qo3jb6poDQp4tswyi5kGi/cZJGzu2YwH0uq0T+7imrc1oQTF0qFz8XBeAIQCfZihf26s8RyzLU4sUsOyPE8qTTnTZ7JXy0MMkmYZWAc+cGX2tHqkSy/LNIVFeWIiWTmFerILCqVPcOHnae5iTURLaCXGBISUxLjez5OmGnUFupn9a6gEz1a1A2/i4OZA8Vq4zthayr4Tuio+26oEXO1tA+a/wlqUmhSjJHa9/p/g4t1ZdNhe7d8GuVPNH7uQrKJvMGFwLL5gqL6sYNE3tj/ZinLXxagsdfcq67Lz+koo2HbHAfrDJW3GmXaZ2F+srITZkW9fEiBb/2pzkF+RoD+Ya8sApXNghB4F4aziWI8yI/pSiaR7AiIjpDAE8O6HiHpWbfCZbG0na29oYVjIreFer5hr6h+aEtnK67/grnDAJAqytdduwFK/of1PrqJFkxKen583JjlIkrvKlyKXkm7VxnQVZIenYZgl14i9aaQ5r76Le7Uh2mi6TzMX1ww5mhJw9XiVPRrHCq2LZXAXKZY9VB/NRxvC9lo9odR3woQMKaZnB0wKv/k3MgLUkBNBrX7cnNtXgNmgrhBq88tbNZzVbSCCnqasMPLWYKn8kch9xVxYiI=
  app: murmuring-hollows-41113
  on:
    repo: complicationlamp/flashcard-react-app-api
